---
# tasks/main.yml

- name: Configuração inicial do diretório e arquivos base
  import_tasks: setup.yml
  tags: setup

- name: Criação do arquivo .env
  import_tasks: env.yml
  tags: env

- name: Criação do ambiente virtual venv
  import_tasks: venv.yml
  tags: venv

- name: Instalação das dependências
  import_tasks: deps.yml
  tags: deps

- name: Copia script run.sh
  import_tasks: run.yml
  tags: run

- name: Criação do cron job
  import_tasks: cron.yml
  tags: cron

- name: Execução imediata do script
  import_tasks: exec.yml
  tags: exec
